name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '8.0.303' # The .NET SDK version to use

jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore   
      
    - name: Build
      run: dotnet build .\acc-hotrun-run-compare\acc-hotrun-run-compare.csproj

    - name: Get XML Info
      id: getxmlversion
      uses: mavrosxristoforos/get-xml-info@2.0 
      with:
        xml-file: '.\acc-hotrun-run-compare\version.xml'
        xpath: '//version'

    - name: Echo version
      env: 
        VERSION_CONTEXT: ${{ steps.getxmlversion.outputs.info }}
      run: echo "$VERSION_CONTEXT"
      
    
    - name: Automatic testing
      run: dotnet test
