name: buildandrelease

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '8.0.303' # The .NET SDK version to use

jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore   
      
    - name: Build
      run: dotnet build .\acc-hotrun-run-compare\acc-hotrun-run-compare.csproj

    - name: Get XML Info
      id: getxmlversion
      uses: mavrosxristoforos/get-xml-info@2.0 
      with:
        xml-file: '.\acc-hotrun-run-compare\version.xml'
        xpath: '//version'

    - name: Echo version
      env: 
        VERSION_CONTEXT: ${{ steps.getxmlversion.outputs.info }}
      run: echo "$VERSION_CONTEXT"
    
    - name: Automatic testing
      run: dotnet test

    - name: Release version
      id: create_release_github
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release
        release_name: ${{ steps.getxmlversion.outputs.info }}
        body: New release with version ${{ steps.getxmlversion.outputs.info }}
        draft: false
        prerelease: false

    - name: Create Release Build
      id: create_release_build
      run: dotnet publish --output "./bin/release" --runtime win-x64 --configuration Release -p:PusblishSingleFile=true

    - name: Create zip file of release
      id: create_release_file
      shell: pwsh
      run: Compress-Archive bin/release/* releasefile.zip

    - name: Push release zip to GitHub
      id: publish_release_file
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release_github.outputs.upload_url }}
        asset_path: releasefile.zip
        asset_name: release_v${{ steps.getxmlversion.outputs.info }}.zip
        asset_content_type: application/zip
